# Generated by Django 2.2.14 on 2020-12-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_auto_20201203_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
